#!/usr/bin/env bash
# Copy real suite photos from haven/Images into public/images/haven
# and write src/data/havenPhotos.ts
#
# Run from the repo root on your Mac:
#   bash scripts/port-haven-photos.sh
#   git add public/images/haven src/data/havenPhotos.ts
#   git commit -m "photos: Haven interiors"
#   git pull --rebase origin main && git push origin main

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="$ROOT/haven/Images"
DEST="$ROOT/public/images/haven"
OUT="$ROOT/src/data/havenPhotos.ts"

if [[ ! -d "$SRC" ]]; then
  echo "No folder at $SRC"
  echo "Expected haven/Images/{Elowen,Hidden Hollow,River Blosom,Water Mark,Exterior}"
  exit 1
fi

slug_for() {
  case "$1" in
    Elowen) echo elowen ;;
    "Hidden Hollow") echo hidden-hollow ;;
    "River Blosom"|"River Blossom") echo river-blossom ;;
    "Water Mark") echo water-mark ;;
    Exterior|exterior) echo exterior ;;
    *) echo "" ;;
  esac
}

mkdir -p "$DEST"
# keep mockups from colliding with interiors
mkdir -p "$DEST/_mockups"
shopt -s nullglob
for leftover in "$DEST"/*.jpg "$DEST"/*.jpeg "$DEST"/*.png; do
  [[ -f "$leftover" ]] && mv "$leftover" "$DEST/_mockups/" || true
done

declare -a ORDERED_SLUGS=(elowen hidden-hollow river-blossom water-mark exterior)
declare -A FILES=()

for dir in "$SRC"/*; do
  [[ -d "$dir" ]] || continue
  name="$(basename "$dir")"
  slug="$(slug_for "$name")"
  if [[ -z "$slug" ]]; then
    echo "Skipping unmapped folder: $name"
    continue
  fi

  mkdir -p "$DEST/$slug"
  rm -f "$DEST/$slug"/*

  n=0
  # sort so Bedroom / Kitchen order is stable
  while IFS= read -r -d '' srcfile; do
    n=$((n + 1))
    printf -v destfile "%s/%s/%s-%02d.jpg" "$DEST" "$slug" "$slug" "$n"
    ext="${srcfile##*.}"
    ext_lc="$(printf '%s' "$ext" | tr '[:upper:]' '[:lower:]')"
    if [[ "$ext_lc" == "jpg" || "$ext_lc" == "jpeg" ]]; then
      cp "$srcfile" "$destfile"
    elif command -v sips >/dev/null 2>&1; then
      sips -s format jpeg "$srcfile" --out "$destfile" >/dev/null
    else
      cp "$srcfile" "$destfile"
    fi
    echo "  $name  ->  ${destfile#$ROOT/}"
  done < <(find "$dir" -type f \( -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.png' -o -iname '*.webp' -o -iname '*.heic' \) -print0 | sort -z)

  echo "$slug: $n files"
  FILES[$slug]=$n
done

{
  echo "// Generated by scripts/port-haven-photos.sh — do not edit by hand"
  echo "export const HAVEN_PHOTOS = {"
  for slug in "${ORDERED_SLUGS[@]}"; do
    count="${FILES[$slug]:-0}"
    echo "  \"$slug\": ["
    if [[ "$count" -gt 0 ]]; then
      i=1
      while [[ $i -le $count ]]; do
        printf -v num "%02d" "$i"
        comma=","
        [[ $i -eq $count ]] && comma=""
        echo "    \"/images/haven/$slug/$slug-$num.jpg\"$comma"
        i=$((i + 1))
      done
    fi
    echo "  ],"
  done
  echo "} as const;"
} > "$OUT"

echo
echo "Wrote $OUT"
echo "Next:"
echo "  git add public/images/haven src/data/havenPhotos.ts"
echo "  git commit -m \"photos: Haven interiors\""
echo "  git pull --rebase origin main && git push origin main"
