#!/usr/bin/env bash
# Copy real suite photos from haven/Images into public/images/haven
# macOS ships Bash 3.2 — no associative arrays.
#
#   bash scripts/port-haven-photos.sh
#   git add public/images/haven src/data/havenPhotos.ts
#   git commit -m "photos: Haven interiors"
#   git pull --rebase origin main && git push origin main

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="$ROOT/haven/Images"
DEST="$ROOT/public/images/haven"
OUT="$ROOT/src/data/havenPhotos.ts"

if [ ! -d "$SRC" ]; then
  echo "No folder at $SRC"
  echo "Expected haven/Images/{Elowen,Hidden Hollow,River Blosom,Water Mark,Exterior}"
  exit 1
fi

slug_for() {
  case "$1" in
    Elowen) printf '%s' elowen ;;
    "Hidden Hollow") printf '%s' hidden-hollow ;;
    "River Blosom"|"River Blossom") printf '%s' river-blossom ;;
    "Water Mark") printf '%s' water-mark ;;
    Exterior|exterior) printf '%s' exterior ;;
    *) printf '%s' "" ;;
  esac
}

mkdir -p "$DEST/_mockups"
for leftover in "$DEST"/*.jpg "$DEST"/*.jpeg "$DEST"/*.png; do
  if [ -f "$leftover" ]; then
    mv "$leftover" "$DEST/_mockups/"
  fi
done

COUNT_ELOWEN=0
COUNT_HIDDEN=0
COUNT_RIVER=0
COUNT_WATER=0
COUNT_EXTERIOR=0

set_count() {
  case "$1" in
    elowen) COUNT_ELOWEN=$2 ;;
    hidden-hollow) COUNT_HIDDEN=$2 ;;
    river-blossom) COUNT_RIVER=$2 ;;
    water-mark) COUNT_WATER=$2 ;;
    exterior) COUNT_EXTERIOR=$2 ;;
  esac
}

get_count() {
  case "$1" in
    elowen) echo "$COUNT_ELOWEN" ;;
    hidden-hollow) echo "$COUNT_HIDDEN" ;;
    river-blossom) echo "$COUNT_RIVER" ;;
    water-mark) echo "$COUNT_WATER" ;;
    exterior) echo "$COUNT_EXTERIOR" ;;
    *) echo 0 ;;
  esac
}

for dir in "$SRC"/*; do
  [ -d "$dir" ] || continue
  name="$(basename "$dir")"
  slug="$(slug_for "$name")"
  if [ -z "$slug" ]; then
    echo "Skipping unmapped folder: $name"
    continue
  fi

  mkdir -p "$DEST/$slug"
  rm -f "$DEST/$slug"/*

  n=0
  # Portable file list (no find -print0 required)
  OLDIFS=$IFS
  IFS=$'\n'
  for srcfile in $(find "$dir" -type f \( -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.png' -o -iname '*.webp' -o -iname '*.heic' \) | sort); do
    [ -f "$srcfile" ] || continue
    n=$((n + 1))
    destfile=$(printf '%s/%s/%s-%02d.jpg' "$DEST" "$slug" "$slug" "$n")
    ext=$(printf '%s' "${srcfile##*.}" | tr '[:upper:]' '[:lower:]')
    if [ "$ext" = "jpg" ] || [ "$ext" = "jpeg" ]; then
      cp "$srcfile" "$destfile"
    elif command -v sips >/dev/null 2>&1; then
      sips -s format jpeg "$srcfile" --out "$destfile" >/dev/null
    else
      cp "$srcfile" "$destfile"
    fi
    echo "  $name  ->  ${destfile#$ROOT/}"
  done
  IFS=$OLDIFS

  set_count "$slug" "$n"
  echo "$slug: $n files"
done

{
  echo "// Generated by scripts/port-haven-photos.sh — do not edit by hand"
  echo "export const HAVEN_PHOTOS = {"
  for slug in elowen hidden-hollow river-blossom water-mark exterior; do
    count=$(get_count "$slug")
    echo "  \"$slug\": ["
    if [ "$count" -gt 0 ]; then
      i=1
      while [ "$i" -le "$count" ]; do
        num=$(printf '%02d' "$i")
        if [ "$i" -eq "$count" ]; then
          echo "    \"/images/haven/$slug/$slug-$num.jpg\""
        else
          echo "    \"/images/haven/$slug/$slug-$num.jpg\","
        fi
        i=$((i + 1))
      done
    fi
    echo "  ],"
  done
  echo "} as const;"
} > "$OUT"

echo
echo "Wrote $OUT"
echo "Next:"
echo "  git add public/images/haven src/data/havenPhotos.ts"
echo "  git commit -m \"photos: Haven interiors\""
echo "  git pull --rebase origin main && git push origin main"
