import type { ShapeSeed } from "@/brand/engine";

function rune(path: ShapeSeed["paths"]["rune"]): ShapeSeed {
  return {
    version: 1,
    tier: "rune",
    grid: { rune: 4 },
    paths: { rune: path },
    closed: { rune: true },
    params: { arcResolution: 128, rune: { radiusRatio: 0.37 } },
    layers: { mode: "overlay", rune: { color: "#161718", z: 1 } },
    origin: "designer",
  };
}

/** Official June 2026 seeds. Old names dropped. Order is the deck order. */
export const OFFICIAL: { id: string; label: string; seed: ShapeSeed }[] = [
  {
    id: "i",
    label: "Rune I",
    seed: rune([
      { cell: [0, 3], side: "auto" },
      { cell: [0, 2], side: "b" },
      { cell: [0, 1], side: "auto" },
      { cell: [1, 0], side: "auto" },
      { cell: [2, 0], side: "auto" },
      { cell: [2, 1], side: "auto" },
      { cell: [3, 2], side: "auto" },
      { cell: [2, 3], side: "auto" },
      { cell: [1, 3], side: "auto" },
      { cell: [2, 2], side: "auto" },
      { cell: [1, 2], side: "auto" },
      { cell: [1, 1], side: "auto" },
    ]),
  },
  {
    id: "ii",
    label: "Rune II",
    seed: rune([
      { cell: [0, 0], side: "auto" },
      { cell: [1, 1], side: "auto" },
      { cell: [2, 0], side: "auto" },
      { cell: [3, 1], side: "auto" },
      { cell: [2, 2], side: "auto" },
      { cell: [3, 3], side: "auto" },
      { cell: [1, 3], side: "auto" },
      { cell: [1, 2], side: "auto" },
      { cell: [0, 3], side: "auto" },
    ]),
  },
  {
    id: "iii",
    label: "Rune III",
    seed: rune([
      { cell: [1, 1], side: "auto" },
      { cell: [2, 0], side: "auto" },
      { cell: [3, 1], side: "auto" },
      { cell: [2, 1], side: "auto" },
      { cell: [3, 2], side: "auto" },
      { cell: [2, 3], side: "auto" },
      { cell: [1, 3], side: "auto" },
      { cell: [0, 3], side: "auto" },
      { cell: [0, 2], side: "b" },
    ]),
  },
  {
    id: "iv",
    label: "Rune IV",
    seed: rune([
      { cell: [2, 3], side: "auto" },
      { cell: [2, 2], side: "auto" },
      { cell: [3, 2], side: "auto" },
      { cell: [3, 0], side: "auto" },
      { cell: [2, 0], side: "auto" },
      { cell: [0, 0], side: "auto" },
      { cell: [0, 2], side: "auto" },
      { cell: [1, 1], side: "auto" },
      { cell: [1, 3], side: "auto" },
    ]),
  },
  {
    id: "v",
    label: "Rune V",
    seed: rune([
      { cell: [0, 3], side: "auto" },
      { cell: [0, 1], side: "auto" },
      { cell: [1, 1], side: "auto" },
      { cell: [1, 0], side: "auto" },
      { cell: [2, 1], side: "auto" },
      { cell: [3, 1], side: "auto" },
      { cell: [3, 2], side: "auto" },
      { cell: [2, 2], side: "auto" },
      { cell: [1, 3], side: "b" },
    ]),
  },
  {
    id: "vi",
    label: "Rune VI",
    seed: rune([
      { cell: [2, 0], side: "auto" },
      { cell: [2, 1], side: "auto" },
      { cell: [3, 2], side: "auto" },
      { cell: [2, 2], side: "auto" },
      { cell: [3, 3], side: "auto" },
      { cell: [1, 3], side: "auto" },
      { cell: [0, 3], side: "b" },
      { cell: [1, 1], side: "auto" },
      { cell: [0, 0], side: "auto" },
    ]),
  },
  {
    id: "vii",
    label: "Rune VII",
    seed: rune([
      { cell: [0, 0], side: "auto" },
      { cell: [1, 1], side: "auto" },
      { cell: [1, 0], side: "auto" },
      { cell: [3, 1], side: "auto" },
      { cell: [3, 3], side: "auto" },
      { cell: [1, 3], side: "auto" },
      { cell: [2, 2], side: "auto" },
      { cell: [1, 2], side: "auto" },
      { cell: [0, 2], side: "auto" },
    ]),
  },
  {
    id: "viii",
    label: "Rune VIII",
    seed: rune([
      { cell: [2, 0], side: "b" },
      { cell: [3, 0], side: "auto" },
      { cell: [2, 1], side: "auto" },
      { cell: [3, 1], side: "auto" },
      { cell: [3, 2], side: "b" },
      { cell: [3, 3], side: "auto" },
      { cell: [2, 2], side: "auto" },
      { cell: [2, 3], side: "auto" },
      { cell: [0, 3], side: "auto" },
      { cell: [0, 2], side: "auto" },
      { cell: [1, 2], side: "auto" },
      { cell: [0, 1], side: "auto" },
      { cell: [0, 0], side: "auto" },
    ]),
  },
  {
    id: "ix",
    label: "Rune IX",
    seed: rune([
      { cell: [0, 0], side: "auto" },
      { cell: [2, 0], side: "auto" },
      { cell: [2, 1], side: "auto" },
      { cell: [3, 2], side: "auto" },
      { cell: [2, 3], side: "auto" },
      { cell: [2, 2], side: "auto" },
      { cell: [0, 3], side: "auto" },
      { cell: [0, 2], side: "auto" },
      { cell: [1, 1], side: "auto" },
    ]),
  },
  {
    id: "x",
    label: "Rune X",
    seed: rune([
      { cell: [0, 2], side: "b" },
      { cell: [0, 1], side: "auto" },
      { cell: [1, 0], side: "auto" },
      { cell: [2, 1], side: "auto" },
      { cell: [3, 0], side: "auto" },
      { cell: [3, 1], side: "auto" },
      { cell: [3, 3], side: "auto" },
      { cell: [1, 3], side: "b" },
      { cell: [0, 3], side: "auto" },
    ]),
  },
  {
    id: "xi",
    label: "Rune XI",
    seed: rune([
      { cell: [0, 0], side: "auto" },
      { cell: [3, 0], side: "auto" },
      { cell: [1, 1], side: "auto" },
      { cell: [3, 1], side: "auto" },
      { cell: [2, 3], side: "auto" },
      { cell: [1, 2], side: "auto" },
      { cell: [0, 2], side: "a" },
      { cell: [0, 1], side: "b" },
    ]),
  },
];

export const LINES = ["UNEARTH SELF", "BADLANDS BOOTCAMP", "ADVENTURE TOURISM"] as const;

export const GROUNDS = [
  { id: "fossil", label: "Fossil", hex: "#F8F0ED", photo: null },
  { id: "coal", label: "Coal", hex: "#161718", photo: null },
  { id: "shale", label: "Shale", hex: "#423530", photo: null },
  { id: "clear", label: "Clear", hex: null, photo: null },
  { id: "hoodoos", label: "Hoodoos", hex: "#161718", photo: "/images/exp-hoodoos.jpg" },
  { id: "dusk", label: "Dusk", hex: "#161718", photo: "/images/hero-badlands-dusk.jpg" },
  { id: "canyon", label: "Canyon", hex: "#161718", photo: "/images/exp-canyon.jpg" },
  { id: "rolling", label: "Rolling", hex: "#161718", photo: "/images/exp-rolling.jpg" },
] as const;
