/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BasecampRouteImport } from './routes/basecamp'
import { Route as BootcampRouteImport } from './routes/bootcamp'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as D14RouteImport } from './routes/d14'
import { Route as FoundRouteImport } from './routes/found'
import { Route as HavenRouteImport } from './routes/haven'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as QuestRouteImport } from './routes/quest'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SpringRouteImport } from './routes/spring'
import { Route as TheWorkRouteImport } from './routes/the-work'
import { Route as VisitRouteImport } from './routes/visit'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminBotsRouteImport } from './routes/admin.bots'
import { Route as AdminFridayRouteImport } from './routes/admin.friday'
import { Route as AdminInventoryRouteImport } from './routes/admin.inventory'
import { Route as AdminMoneyRouteImport } from './routes/admin.money'
import { Route as AdminPipelineRouteImport } from './routes/admin.pipeline'
import { Route as AdminRiskRouteImport } from './routes/admin.risk'
import { Route as AdminSocialsRouteImport } from './routes/admin.socials'
import { Route as BookRetreatRouteImport } from './routes/book.retreat'
import { Route as BookTreatmentRouteImport } from './routes/book.treatment'
import { Route as D14IndexRouteImport } from './routes/d14.index'
import { Route as D14BasecampRouteImport } from './routes/d14.basecamp'
import { Route as D14SeamRouteImport } from './routes/d14.seam'
import { Route as D14SpecimenRouteImport } from './routes/d14.specimen'
import { Route as ForTeamsRouteImport } from './routes/for.teams'
import { Route as HavenIndexRouteImport } from './routes/haven.index'
import { Route as HavenSlugRouteImport } from './routes/haven.$slug'
import { Route as JournalIndexRouteImport } from './routes/journal.index'
import { Route as JournalSlugRouteImport } from './routes/journal.$slug'
import { Route as QuestIndexRouteImport } from './routes/quest.index'
import { Route as QuestAdminRouteImport } from './routes/quest.admin'
import { Route as QuestBoundaryRouteImport } from './routes/quest.boundary'
import { Route as QuestExperimentRouteImport } from './routes/quest.experiment'
import { Route as QuestMirrorRouteImport } from './routes/quest.mirror'
import { Route as QuestPlayRouteImport } from './routes/quest.play'
import { Route as QuestRecorderRouteImport } from './routes/quest.recorder'
import { Route as QuestRecoverRouteImport } from './routes/quest.recover'
import { Route as QuestRunesRouteImport } from './routes/quest.runes'
import { Route as QuestShuttleRouteImport } from './routes/quest.shuttle'
import { Route as QuestSpecimenRouteImport } from './routes/quest.specimen'
import { Route as QuestThirtyRouteImport } from './routes/quest.thirty'
import { Route as QuestTodayRouteImport } from './routes/quest.today'
import { Route as QuestAdminIndexRouteImport } from './routes/quest.admin.index'
import { Route as QuestAdminAfterRouteImport } from './routes/quest.admin.after'
import { Route as QuestAdminBroadcastRouteImport } from './routes/quest.admin.broadcast'
import { Route as QuestAdminLiveRouteImport } from './routes/quest.admin.live'
import { Route as QuestAdminPackRouteImport } from './routes/quest.admin.pack'
import { Route as QuestAdminPaperRouteImport } from './routes/quest.admin.paper'
import { Route as QuestAdminRosterRouteImport } from './routes/quest.admin.roster'
import { Route as QuestAdminSafetyRouteImport } from './routes/quest.admin.safety'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BasecampRoute = BasecampRouteImport.update({
  id: '/basecamp',
  path: '/basecamp',
  getParentRoute: () => rootRouteImport,
} as any)
const BootcampRoute = BootcampRouteImport.update({
  id: '/bootcamp',
  path: '/bootcamp',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const D14Route = D14RouteImport.update({
  id: '/d14',
  path: '/d14',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundRoute = FoundRouteImport.update({
  id: '/found',
  path: '/found',
  getParentRoute: () => rootRouteImport,
} as any)
const HavenRoute = HavenRouteImport.update({
  id: '/haven',
  path: '/haven',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestRoute = QuestRouteImport.update({
  id: '/quest',
  path: '/quest',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SpringRoute = SpringRouteImport.update({
  id: '/spring',
  path: '/spring',
  getParentRoute: () => rootRouteImport,
} as any)
const TheWorkRoute = TheWorkRouteImport.update({
  id: '/the-work',
  path: '/the-work',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitRoute = VisitRouteImport.update({
  id: '/visit',
  path: '/visit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBotsRoute = AdminBotsRouteImport.update({
  id: '/bots',
  path: '/bots',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFridayRoute = AdminFridayRouteImport.update({
  id: '/friday',
  path: '/friday',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMoneyRoute = AdminMoneyRouteImport.update({
  id: '/money',
  path: '/money',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPipelineRoute = AdminPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRiskRoute = AdminRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSocialsRoute = AdminSocialsRouteImport.update({
  id: '/socials',
  path: '/socials',
  getParentRoute: () => AdminRoute,
} as any)
const BookRetreatRoute = BookRetreatRouteImport.update({
  id: '/book/retreat',
  path: '/book/retreat',
  getParentRoute: () => rootRouteImport,
} as any)
const BookTreatmentRoute = BookTreatmentRouteImport.update({
  id: '/book/treatment',
  path: '/book/treatment',
  getParentRoute: () => rootRouteImport,
} as any)
const D14IndexRoute = D14IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => D14Route,
} as any)
const D14BasecampRoute = D14BasecampRouteImport.update({
  id: '/basecamp',
  path: '/basecamp',
  getParentRoute: () => D14Route,
} as any)
const D14SeamRoute = D14SeamRouteImport.update({
  id: '/seam',
  path: '/seam',
  getParentRoute: () => D14Route,
} as any)
const D14SpecimenRoute = D14SpecimenRouteImport.update({
  id: '/specimen',
  path: '/specimen',
  getParentRoute: () => D14Route,
} as any)
const ForTeamsRoute = ForTeamsRouteImport.update({
  id: '/for/teams',
  path: '/for/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const HavenIndexRoute = HavenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HavenRoute,
} as any)
const HavenSlugRoute = HavenSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => HavenRoute,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JournalRoute,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => JournalRoute,
} as any)
const QuestIndexRoute = QuestIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => QuestRoute,
} as any)
const QuestAdminRoute = QuestAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => QuestRoute,
} as any)
const QuestBoundaryRoute = QuestBoundaryRouteImport.update({
  id: '/boundary',
  path: '/boundary',
  getParentRoute: () => QuestRoute,
} as any)
const QuestExperimentRoute = QuestExperimentRouteImport.update({
  id: '/experiment',
  path: '/experiment',
  getParentRoute: () => QuestRoute,
} as any)
const QuestMirrorRoute = QuestMirrorRouteImport.update({
  id: '/mirror',
  path: '/mirror',
  getParentRoute: () => QuestRoute,
} as any)
const QuestPlayRoute = QuestPlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => QuestRoute,
} as any)
const QuestRecorderRoute = QuestRecorderRouteImport.update({
  id: '/recorder',
  path: '/recorder',
  getParentRoute: () => QuestRoute,
} as any)
const QuestRecoverRoute = QuestRecoverRouteImport.update({
  id: '/recover',
  path: '/recover',
  getParentRoute: () => QuestRoute,
} as any)
const QuestRunesRoute = QuestRunesRouteImport.update({
  id: '/runes',
  path: '/runes',
  getParentRoute: () => QuestRoute,
} as any)
const QuestShuttleRoute = QuestShuttleRouteImport.update({
  id: '/shuttle',
  path: '/shuttle',
  getParentRoute: () => QuestRoute,
} as any)
const QuestSpecimenRoute = QuestSpecimenRouteImport.update({
  id: '/specimen',
  path: '/specimen',
  getParentRoute: () => QuestRoute,
} as any)
const QuestThirtyRoute = QuestThirtyRouteImport.update({
  id: '/thirty',
  path: '/thirty',
  getParentRoute: () => QuestRoute,
} as any)
const QuestTodayRoute = QuestTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => QuestRoute,
} as any)
const QuestAdminIndexRoute = QuestAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => QuestAdminRoute,
} as any)
const QuestAdminAfterRoute = QuestAdminAfterRouteImport.update({
  id: '/after',
  path: '/after',
  getParentRoute: () => QuestAdminRoute,
} as any)
const QuestAdminBroadcastRoute = QuestAdminBroadcastRouteImport.update({
  id: '/broadcast',
  path: '/broadcast',
  getParentRoute: () => QuestAdminRoute,
} as any)
const QuestAdminLiveRoute = QuestAdminLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => QuestAdminRoute,
} as any)
const QuestAdminPackRoute = QuestAdminPackRouteImport.update({
  id: '/pack',
  path: '/pack',
  getParentRoute: () => QuestAdminRoute,
} as any)
const QuestAdminPaperRoute = QuestAdminPaperRouteImport.update({
  id: '/paper',
  path: '/paper',
  getParentRoute: () => QuestAdminRoute,
} as any)
const QuestAdminRosterRoute = QuestAdminRosterRouteImport.update({
  id: '/roster',
  path: '/roster',
  getParentRoute: () => QuestAdminRoute,
} as any)
const QuestAdminSafetyRoute = QuestAdminSafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => QuestAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/basecamp': typeof BasecampRoute
  '/bootcamp': typeof BootcampRoute
  '/builder': typeof BuilderRoute
  '/community': typeof CommunityRoute
  '/d14': typeof D14RouteWithChildren
  '/found': typeof FoundRoute
  '/haven': typeof HavenRouteWithChildren
  '/journal': typeof JournalRouteWithChildren
  '/login': typeof LoginRoute
  '/quest': typeof QuestRouteWithChildren
  '/shop': typeof ShopRoute
  '/spring': typeof SpringRoute
  '/the-work': typeof TheWorkRoute
  '/visit': typeof VisitRoute
  '/admin/bots': typeof AdminBotsRoute
  '/admin/friday': typeof AdminFridayRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/money': typeof AdminMoneyRoute
  '/admin/pipeline': typeof AdminPipelineRoute
  '/admin/risk': typeof AdminRiskRoute
  '/admin/socials': typeof AdminSocialsRoute
  '/book/retreat': typeof BookRetreatRoute
  '/book/treatment': typeof BookTreatmentRoute
  '/d14/basecamp': typeof D14BasecampRoute
  '/d14/seam': typeof D14SeamRoute
  '/d14/specimen': typeof D14SpecimenRoute
  '/for/teams': typeof ForTeamsRoute
  '/haven/$slug': typeof HavenSlugRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/quest/admin': typeof QuestAdminRouteWithChildren
  '/quest/boundary': typeof QuestBoundaryRoute
  '/quest/experiment': typeof QuestExperimentRoute
  '/quest/mirror': typeof QuestMirrorRoute
  '/quest/play': typeof QuestPlayRoute
  '/quest/recorder': typeof QuestRecorderRoute
  '/quest/recover': typeof QuestRecoverRoute
  '/quest/runes': typeof QuestRunesRoute
  '/quest/shuttle': typeof QuestShuttleRoute
  '/quest/specimen': typeof QuestSpecimenRoute
  '/quest/thirty': typeof QuestThirtyRoute
  '/quest/today': typeof QuestTodayRoute
  '/admin/': typeof AdminIndexRoute
  '/d14/': typeof D14IndexRoute
  '/haven/': typeof HavenIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/quest/': typeof QuestIndexRoute
  '/quest/admin/after': typeof QuestAdminAfterRoute
  '/quest/admin/broadcast': typeof QuestAdminBroadcastRoute
  '/quest/admin/live': typeof QuestAdminLiveRoute
  '/quest/admin/pack': typeof QuestAdminPackRoute
  '/quest/admin/paper': typeof QuestAdminPaperRoute
  '/quest/admin/roster': typeof QuestAdminRosterRoute
  '/quest/admin/safety': typeof QuestAdminSafetyRoute
  '/quest/admin/': typeof QuestAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/basecamp': typeof BasecampRoute
  '/bootcamp': typeof BootcampRoute
  '/builder': typeof BuilderRoute
  '/community': typeof CommunityRoute
  '/found': typeof FoundRoute
  '/login': typeof LoginRoute
  '/shop': typeof ShopRoute
  '/spring': typeof SpringRoute
  '/the-work': typeof TheWorkRoute
  '/visit': typeof VisitRoute
  '/admin/bots': typeof AdminBotsRoute
  '/admin/friday': typeof AdminFridayRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/money': typeof AdminMoneyRoute
  '/admin/pipeline': typeof AdminPipelineRoute
  '/admin/risk': typeof AdminRiskRoute
  '/admin/socials': typeof AdminSocialsRoute
  '/book/retreat': typeof BookRetreatRoute
  '/book/treatment': typeof BookTreatmentRoute
  '/d14/basecamp': typeof D14BasecampRoute
  '/d14/seam': typeof D14SeamRoute
  '/d14/specimen': typeof D14SpecimenRoute
  '/for/teams': typeof ForTeamsRoute
  '/haven/$slug': typeof HavenSlugRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/quest/boundary': typeof QuestBoundaryRoute
  '/quest/experiment': typeof QuestExperimentRoute
  '/quest/mirror': typeof QuestMirrorRoute
  '/quest/play': typeof QuestPlayRoute
  '/quest/recorder': typeof QuestRecorderRoute
  '/quest/recover': typeof QuestRecoverRoute
  '/quest/runes': typeof QuestRunesRoute
  '/quest/shuttle': typeof QuestShuttleRoute
  '/quest/specimen': typeof QuestSpecimenRoute
  '/quest/thirty': typeof QuestThirtyRoute
  '/quest/today': typeof QuestTodayRoute
  '/admin': typeof AdminIndexRoute
  '/d14': typeof D14IndexRoute
  '/haven': typeof HavenIndexRoute
  '/journal': typeof JournalIndexRoute
  '/quest': typeof QuestIndexRoute
  '/quest/admin/after': typeof QuestAdminAfterRoute
  '/quest/admin/broadcast': typeof QuestAdminBroadcastRoute
  '/quest/admin/live': typeof QuestAdminLiveRoute
  '/quest/admin/pack': typeof QuestAdminPackRoute
  '/quest/admin/paper': typeof QuestAdminPaperRoute
  '/quest/admin/roster': typeof QuestAdminRosterRoute
  '/quest/admin/safety': typeof QuestAdminSafetyRoute
  '/quest/admin': typeof QuestAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/basecamp': typeof BasecampRoute
  '/bootcamp': typeof BootcampRoute
  '/builder': typeof BuilderRoute
  '/community': typeof CommunityRoute
  '/d14': typeof D14RouteWithChildren
  '/found': typeof FoundRoute
  '/haven': typeof HavenRouteWithChildren
  '/journal': typeof JournalRouteWithChildren
  '/login': typeof LoginRoute
  '/quest': typeof QuestRouteWithChildren
  '/shop': typeof ShopRoute
  '/spring': typeof SpringRoute
  '/the-work': typeof TheWorkRoute
  '/visit': typeof VisitRoute
  '/admin/bots': typeof AdminBotsRoute
  '/admin/friday': typeof AdminFridayRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/money': typeof AdminMoneyRoute
  '/admin/pipeline': typeof AdminPipelineRoute
  '/admin/risk': typeof AdminRiskRoute
  '/admin/socials': typeof AdminSocialsRoute
  '/book/retreat': typeof BookRetreatRoute
  '/book/treatment': typeof BookTreatmentRoute
  '/d14/basecamp': typeof D14BasecampRoute
  '/d14/seam': typeof D14SeamRoute
  '/d14/specimen': typeof D14SpecimenRoute
  '/for/teams': typeof ForTeamsRoute
  '/haven/$slug': typeof HavenSlugRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/quest/admin': typeof QuestAdminRouteWithChildren
  '/quest/boundary': typeof QuestBoundaryRoute
  '/quest/experiment': typeof QuestExperimentRoute
  '/quest/mirror': typeof QuestMirrorRoute
  '/quest/play': typeof QuestPlayRoute
  '/quest/recorder': typeof QuestRecorderRoute
  '/quest/recover': typeof QuestRecoverRoute
  '/quest/runes': typeof QuestRunesRoute
  '/quest/shuttle': typeof QuestShuttleRoute
  '/quest/specimen': typeof QuestSpecimenRoute
  '/quest/thirty': typeof QuestThirtyRoute
  '/quest/today': typeof QuestTodayRoute
  '/admin/': typeof AdminIndexRoute
  '/d14/': typeof D14IndexRoute
  '/haven/': typeof HavenIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/quest/': typeof QuestIndexRoute
  '/quest/admin/after': typeof QuestAdminAfterRoute
  '/quest/admin/broadcast': typeof QuestAdminBroadcastRoute
  '/quest/admin/live': typeof QuestAdminLiveRoute
  '/quest/admin/pack': typeof QuestAdminPackRoute
  '/quest/admin/paper': typeof QuestAdminPaperRoute
  '/quest/admin/roster': typeof QuestAdminRosterRoute
  '/quest/admin/safety': typeof QuestAdminSafetyRoute
  '/quest/admin/': typeof QuestAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/basecamp'
    | '/bootcamp'
    | '/builder'
    | '/community'
    | '/d14'
    | '/found'
    | '/haven'
    | '/journal'
    | '/login'
    | '/quest'
    | '/shop'
    | '/spring'
    | '/the-work'
    | '/visit'
    | '/admin/bots'
    | '/admin/friday'
    | '/admin/inventory'
    | '/admin/money'
    | '/admin/pipeline'
    | '/admin/risk'
    | '/admin/socials'
    | '/book/retreat'
    | '/book/treatment'
    | '/d14/basecamp'
    | '/d14/seam'
    | '/d14/specimen'
    | '/for/teams'
    | '/haven/$slug'
    | '/journal/$slug'
    | '/quest/admin'
    | '/quest/boundary'
    | '/quest/experiment'
    | '/quest/mirror'
    | '/quest/play'
    | '/quest/recorder'
    | '/quest/recover'
    | '/quest/runes'
    | '/quest/shuttle'
    | '/quest/specimen'
    | '/quest/thirty'
    | '/quest/today'
    | '/admin/'
    | '/d14/'
    | '/haven/'
    | '/journal/'
    | '/quest/'
    | '/quest/admin/after'
    | '/quest/admin/broadcast'
    | '/quest/admin/live'
    | '/quest/admin/pack'
    | '/quest/admin/paper'
    | '/quest/admin/roster'
    | '/quest/admin/safety'
    | '/quest/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/basecamp'
    | '/bootcamp'
    | '/builder'
    | '/community'
    | '/found'
    | '/login'
    | '/shop'
    | '/spring'
    | '/the-work'
    | '/visit'
    | '/admin/bots'
    | '/admin/friday'
    | '/admin/inventory'
    | '/admin/money'
    | '/admin/pipeline'
    | '/admin/risk'
    | '/admin/socials'
    | '/book/retreat'
    | '/book/treatment'
    | '/d14/basecamp'
    | '/d14/seam'
    | '/d14/specimen'
    | '/for/teams'
    | '/haven/$slug'
    | '/journal/$slug'
    | '/quest/boundary'
    | '/quest/experiment'
    | '/quest/mirror'
    | '/quest/play'
    | '/quest/recorder'
    | '/quest/recover'
    | '/quest/runes'
    | '/quest/shuttle'
    | '/quest/specimen'
    | '/quest/thirty'
    | '/quest/today'
    | '/admin'
    | '/d14'
    | '/haven'
    | '/journal'
    | '/quest'
    | '/quest/admin/after'
    | '/quest/admin/broadcast'
    | '/quest/admin/live'
    | '/quest/admin/pack'
    | '/quest/admin/paper'
    | '/quest/admin/roster'
    | '/quest/admin/safety'
    | '/quest/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/basecamp'
    | '/bootcamp'
    | '/builder'
    | '/community'
    | '/d14'
    | '/found'
    | '/haven'
    | '/journal'
    | '/login'
    | '/quest'
    | '/shop'
    | '/spring'
    | '/the-work'
    | '/visit'
    | '/admin/bots'
    | '/admin/friday'
    | '/admin/inventory'
    | '/admin/money'
    | '/admin/pipeline'
    | '/admin/risk'
    | '/admin/socials'
    | '/book/retreat'
    | '/book/treatment'
    | '/d14/basecamp'
    | '/d14/seam'
    | '/d14/specimen'
    | '/for/teams'
    | '/haven/$slug'
    | '/journal/$slug'
    | '/quest/admin'
    | '/quest/boundary'
    | '/quest/experiment'
    | '/quest/mirror'
    | '/quest/play'
    | '/quest/recorder'
    | '/quest/recover'
    | '/quest/runes'
    | '/quest/shuttle'
    | '/quest/specimen'
    | '/quest/thirty'
    | '/quest/today'
    | '/admin/'
    | '/d14/'
    | '/haven/'
    | '/journal/'
    | '/quest/'
    | '/quest/admin/after'
    | '/quest/admin/broadcast'
    | '/quest/admin/live'
    | '/quest/admin/pack'
    | '/quest/admin/paper'
    | '/quest/admin/roster'
    | '/quest/admin/safety'
    | '/quest/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BasecampRoute: typeof BasecampRoute
  BootcampRoute: typeof BootcampRoute
  BuilderRoute: typeof BuilderRoute
  CommunityRoute: typeof CommunityRoute
  D14Route: typeof D14RouteWithChildren
  FoundRoute: typeof FoundRoute
  HavenRoute: typeof HavenRouteWithChildren
  JournalRoute: typeof JournalRouteWithChildren
  LoginRoute: typeof LoginRoute
  QuestRoute: typeof QuestRouteWithChildren
  ShopRoute: typeof ShopRoute
  SpringRoute: typeof SpringRoute
  TheWorkRoute: typeof TheWorkRoute
  VisitRoute: typeof VisitRoute
  BookRetreatRoute: typeof BookRetreatRoute
  BookTreatmentRoute: typeof BookTreatmentRoute
  ForTeamsRoute: typeof ForTeamsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/basecamp': {
      id: '/basecamp'
      path: '/basecamp'
      fullPath: '/basecamp'
      preLoaderRoute: typeof BasecampRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bootcamp': {
      id: '/bootcamp'
      path: '/bootcamp'
      fullPath: '/bootcamp'
      preLoaderRoute: typeof BootcampRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d14': {
      id: '/d14'
      path: '/d14'
      fullPath: '/d14'
      preLoaderRoute: typeof D14RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/found': {
      id: '/found'
      path: '/found'
      fullPath: '/found'
      preLoaderRoute: typeof FoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/haven': {
      id: '/haven'
      path: '/haven'
      fullPath: '/haven'
      preLoaderRoute: typeof HavenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quest': {
      id: '/quest'
      path: '/quest'
      fullPath: '/quest'
      preLoaderRoute: typeof QuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spring': {
      id: '/spring'
      path: '/spring'
      fullPath: '/spring'
      preLoaderRoute: typeof SpringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/the-work': {
      id: '/the-work'
      path: '/the-work'
      fullPath: '/the-work'
      preLoaderRoute: typeof TheWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visit': {
      id: '/visit'
      path: '/visit'
      fullPath: '/visit'
      preLoaderRoute: typeof VisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bots': {
      id: '/admin/bots'
      path: '/bots'
      fullPath: '/admin/bots'
      preLoaderRoute: typeof AdminBotsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/friday': {
      id: '/admin/friday'
      path: '/friday'
      fullPath: '/admin/friday'
      preLoaderRoute: typeof AdminFridayRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/money': {
      id: '/admin/money'
      path: '/money'
      fullPath: '/admin/money'
      preLoaderRoute: typeof AdminMoneyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pipeline': {
      id: '/admin/pipeline'
      path: '/pipeline'
      fullPath: '/admin/pipeline'
      preLoaderRoute: typeof AdminPipelineRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/risk': {
      id: '/admin/risk'
      path: '/risk'
      fullPath: '/admin/risk'
      preLoaderRoute: typeof AdminRiskRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/socials': {
      id: '/admin/socials'
      path: '/socials'
      fullPath: '/admin/socials'
      preLoaderRoute: typeof AdminSocialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/book/retreat': {
      id: '/book/retreat'
      path: '/book/retreat'
      fullPath: '/book/retreat'
      preLoaderRoute: typeof BookRetreatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/treatment': {
      id: '/book/treatment'
      path: '/book/treatment'
      fullPath: '/book/treatment'
      preLoaderRoute: typeof BookTreatmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d14/': {
      id: '/d14/'
      path: '/'
      fullPath: '/d14/'
      preLoaderRoute: typeof D14IndexRouteImport
      parentRoute: typeof D14Route
    }
    '/d14/basecamp': {
      id: '/d14/basecamp'
      path: '/basecamp'
      fullPath: '/d14/basecamp'
      preLoaderRoute: typeof D14BasecampRouteImport
      parentRoute: typeof D14Route
    }
    '/d14/seam': {
      id: '/d14/seam'
      path: '/seam'
      fullPath: '/d14/seam'
      preLoaderRoute: typeof D14SeamRouteImport
      parentRoute: typeof D14Route
    }
    '/d14/specimen': {
      id: '/d14/specimen'
      path: '/specimen'
      fullPath: '/d14/specimen'
      preLoaderRoute: typeof D14SpecimenRouteImport
      parentRoute: typeof D14Route
    }
    '/for/teams': {
      id: '/for/teams'
      path: '/for/teams'
      fullPath: '/for/teams'
      preLoaderRoute: typeof ForTeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/haven/': {
      id: '/haven/'
      path: '/'
      fullPath: '/haven/'
      preLoaderRoute: typeof HavenIndexRouteImport
      parentRoute: typeof HavenRoute
    }
    '/haven/$slug': {
      id: '/haven/$slug'
      path: '/$slug'
      fullPath: '/haven/$slug'
      preLoaderRoute: typeof HavenSlugRouteImport
      parentRoute: typeof HavenRoute
    }
    '/journal/': {
      id: '/journal/'
      path: '/'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof JournalRoute
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof JournalRoute
    }
    '/quest/': {
      id: '/quest/'
      path: '/'
      fullPath: '/quest/'
      preLoaderRoute: typeof QuestIndexRouteImport
      parentRoute: typeof QuestRoute
    }
    '/quest/admin': {
      id: '/quest/admin'
      path: '/admin'
      fullPath: '/quest/admin'
      preLoaderRoute: typeof QuestAdminRouteImport
      parentRoute: typeof QuestRoute
    }
    '/quest/boundary': {
      id: '/quest/boundary'
      path: '/boundary'
      fullPath: '/quest/boundary'
      preLoaderRoute: typeof QuestBoundaryRouteImport
      parentRoute: typeof QuestRoute
    }
    '/quest/experiment': {
      id: '/quest/experiment'
      path: '/experiment'
      fullPath: '/quest/experiment'
      preLoaderRoute: typeof QuestExperimentRouteImport
      parentRoute: typeof QuestRoute
    }
    '/quest/mirror': {
      id: '/quest/mirror'
      path: '/mirror'
      fullPath: '/quest/mirror'
      preLoaderRoute: typeof QuestMirrorRouteImport
      parentRoute: typeof QuestRoute
    }
    '/quest/play': {
      id: '/quest/play'
      path: '/play'
      fullPath: '/quest/play'
      preLoaderRoute: typeof QuestPlayRouteImport
      parentRoute: typeof QuestRoute
    }
    '/quest/recorder': {
      id: '/quest/recorder'
      path: '/recorder'
      fullPath: '/quest/recorder'
      preLoaderRoute: typeof QuestRecorderRouteImport
      parentRoute: typeof QuestRoute
    }
    '/quest/recover': {
      id: '/quest/recover'
      path: '/recover'
      fullPath: '/quest/recover'
      preLoaderRoute: typeof QuestRecoverRouteImport
      parentRoute: typeof QuestRoute
    }
    '/quest/runes': {
      id: '/quest/runes'
      path: '/runes'
      fullPath: '/quest/runes'
      preLoaderRoute: typeof QuestRunesRouteImport
      parentRoute: typeof QuestRoute
    }
    '/quest/shuttle': {
      id: '/quest/shuttle'
      path: '/shuttle'
      fullPath: '/quest/shuttle'
      preLoaderRoute: typeof QuestShuttleRouteImport
      parentRoute: typeof QuestRoute
    }
    '/quest/specimen': {
      id: '/quest/specimen'
      path: '/specimen'
      fullPath: '/quest/specimen'
      preLoaderRoute: typeof QuestSpecimenRouteImport
      parentRoute: typeof QuestRoute
    }
    '/quest/thirty': {
      id: '/quest/thirty'
      path: '/thirty'
      fullPath: '/quest/thirty'
      preLoaderRoute: typeof QuestThirtyRouteImport
      parentRoute: typeof QuestRoute
    }
    '/quest/today': {
      id: '/quest/today'
      path: '/today'
      fullPath: '/quest/today'
      preLoaderRoute: typeof QuestTodayRouteImport
      parentRoute: typeof QuestRoute
    }
    '/quest/admin/': {
      id: '/quest/admin/'
      path: '/'
      fullPath: '/quest/admin/'
      preLoaderRoute: typeof QuestAdminIndexRouteImport
      parentRoute: typeof QuestAdminRoute
    }
    '/quest/admin/after': {
      id: '/quest/admin/after'
      path: '/after'
      fullPath: '/quest/admin/after'
      preLoaderRoute: typeof QuestAdminAfterRouteImport
      parentRoute: typeof QuestAdminRoute
    }
    '/quest/admin/broadcast': {
      id: '/quest/admin/broadcast'
      path: '/broadcast'
      fullPath: '/quest/admin/broadcast'
      preLoaderRoute: typeof QuestAdminBroadcastRouteImport
      parentRoute: typeof QuestAdminRoute
    }
    '/quest/admin/live': {
      id: '/quest/admin/live'
      path: '/live'
      fullPath: '/quest/admin/live'
      preLoaderRoute: typeof QuestAdminLiveRouteImport
      parentRoute: typeof QuestAdminRoute
    }
    '/quest/admin/pack': {
      id: '/quest/admin/pack'
      path: '/pack'
      fullPath: '/quest/admin/pack'
      preLoaderRoute: typeof QuestAdminPackRouteImport
      parentRoute: typeof QuestAdminRoute
    }
    '/quest/admin/paper': {
      id: '/quest/admin/paper'
      path: '/paper'
      fullPath: '/quest/admin/paper'
      preLoaderRoute: typeof QuestAdminPaperRouteImport
      parentRoute: typeof QuestAdminRoute
    }
    '/quest/admin/roster': {
      id: '/quest/admin/roster'
      path: '/roster'
      fullPath: '/quest/admin/roster'
      preLoaderRoute: typeof QuestAdminRosterRouteImport
      parentRoute: typeof QuestAdminRoute
    }
    '/quest/admin/safety': {
      id: '/quest/admin/safety'
      path: '/safety'
      fullPath: '/quest/admin/safety'
      preLoaderRoute: typeof QuestAdminSafetyRouteImport
      parentRoute: typeof QuestAdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBotsRoute: typeof AdminBotsRoute
  AdminFridayRoute: typeof AdminFridayRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminMoneyRoute: typeof AdminMoneyRoute
  AdminPipelineRoute: typeof AdminPipelineRoute
  AdminRiskRoute: typeof AdminRiskRoute
  AdminSocialsRoute: typeof AdminSocialsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBotsRoute: AdminBotsRoute,
  AdminFridayRoute: AdminFridayRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminMoneyRoute: AdminMoneyRoute,
  AdminPipelineRoute: AdminPipelineRoute,
  AdminRiskRoute: AdminRiskRoute,
  AdminSocialsRoute: AdminSocialsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface D14RouteChildren {
  D14BasecampRoute: typeof D14BasecampRoute
  D14SeamRoute: typeof D14SeamRoute
  D14SpecimenRoute: typeof D14SpecimenRoute
  D14IndexRoute: typeof D14IndexRoute
}

const D14RouteChildren: D14RouteChildren = {
  D14BasecampRoute: D14BasecampRoute,
  D14SeamRoute: D14SeamRoute,
  D14SpecimenRoute: D14SpecimenRoute,
  D14IndexRoute: D14IndexRoute,
}

const D14RouteWithChildren = D14Route._addFileChildren(D14RouteChildren)

interface HavenRouteChildren {
  HavenSlugRoute: typeof HavenSlugRoute
  HavenIndexRoute: typeof HavenIndexRoute
}

const HavenRouteChildren: HavenRouteChildren = {
  HavenSlugRoute: HavenSlugRoute,
  HavenIndexRoute: HavenIndexRoute,
}

const HavenRouteWithChildren = HavenRoute._addFileChildren(HavenRouteChildren)

interface JournalRouteChildren {
  JournalSlugRoute: typeof JournalSlugRoute
  JournalIndexRoute: typeof JournalIndexRoute
}

const JournalRouteChildren: JournalRouteChildren = {
  JournalSlugRoute: JournalSlugRoute,
  JournalIndexRoute: JournalIndexRoute,
}

const JournalRouteWithChildren =
  JournalRoute._addFileChildren(JournalRouteChildren)

interface QuestAdminRouteChildren {
  QuestAdminAfterRoute: typeof QuestAdminAfterRoute
  QuestAdminBroadcastRoute: typeof QuestAdminBroadcastRoute
  QuestAdminLiveRoute: typeof QuestAdminLiveRoute
  QuestAdminPackRoute: typeof QuestAdminPackRoute
  QuestAdminPaperRoute: typeof QuestAdminPaperRoute
  QuestAdminRosterRoute: typeof QuestAdminRosterRoute
  QuestAdminSafetyRoute: typeof QuestAdminSafetyRoute
  QuestAdminIndexRoute: typeof QuestAdminIndexRoute
}

const QuestAdminRouteChildren: QuestAdminRouteChildren = {
  QuestAdminAfterRoute: QuestAdminAfterRoute,
  QuestAdminBroadcastRoute: QuestAdminBroadcastRoute,
  QuestAdminLiveRoute: QuestAdminLiveRoute,
  QuestAdminPackRoute: QuestAdminPackRoute,
  QuestAdminPaperRoute: QuestAdminPaperRoute,
  QuestAdminRosterRoute: QuestAdminRosterRoute,
  QuestAdminSafetyRoute: QuestAdminSafetyRoute,
  QuestAdminIndexRoute: QuestAdminIndexRoute,
}

const QuestAdminRouteWithChildren = QuestAdminRoute._addFileChildren(
  QuestAdminRouteChildren,
)

interface QuestRouteChildren {
  QuestAdminRoute: typeof QuestAdminRouteWithChildren
  QuestBoundaryRoute: typeof QuestBoundaryRoute
  QuestExperimentRoute: typeof QuestExperimentRoute
  QuestMirrorRoute: typeof QuestMirrorRoute
  QuestPlayRoute: typeof QuestPlayRoute
  QuestRecorderRoute: typeof QuestRecorderRoute
  QuestRecoverRoute: typeof QuestRecoverRoute
  QuestRunesRoute: typeof QuestRunesRoute
  QuestShuttleRoute: typeof QuestShuttleRoute
  QuestSpecimenRoute: typeof QuestSpecimenRoute
  QuestThirtyRoute: typeof QuestThirtyRoute
  QuestTodayRoute: typeof QuestTodayRoute
  QuestIndexRoute: typeof QuestIndexRoute
}

const QuestRouteChildren: QuestRouteChildren = {
  QuestAdminRoute: QuestAdminRouteWithChildren,
  QuestBoundaryRoute: QuestBoundaryRoute,
  QuestExperimentRoute: QuestExperimentRoute,
  QuestMirrorRoute: QuestMirrorRoute,
  QuestPlayRoute: QuestPlayRoute,
  QuestRecorderRoute: QuestRecorderRoute,
  QuestRecoverRoute: QuestRecoverRoute,
  QuestRunesRoute: QuestRunesRoute,
  QuestShuttleRoute: QuestShuttleRoute,
  QuestSpecimenRoute: QuestSpecimenRoute,
  QuestThirtyRoute: QuestThirtyRoute,
  QuestTodayRoute: QuestTodayRoute,
  QuestIndexRoute: QuestIndexRoute,
}

const QuestRouteWithChildren = QuestRoute._addFileChildren(QuestRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BasecampRoute: BasecampRoute,
  BootcampRoute: BootcampRoute,
  BuilderRoute: BuilderRoute,
  CommunityRoute: CommunityRoute,
  D14Route: D14RouteWithChildren,
  FoundRoute: FoundRoute,
  HavenRoute: HavenRouteWithChildren,
  JournalRoute: JournalRouteWithChildren,
  LoginRoute: LoginRoute,
  QuestRoute: QuestRouteWithChildren,
  ShopRoute: ShopRoute,
  SpringRoute: SpringRoute,
  TheWorkRoute: TheWorkRoute,
  VisitRoute: VisitRoute,
  BookRetreatRoute: BookRetreatRoute,
  BookTreatmentRoute: BookTreatmentRoute,
  ForTeamsRoute: ForTeamsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
