/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BasecampRouteImport } from './routes/basecamp'
import { Route as BootcampRouteImport } from './routes/bootcamp'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as HavenRouteImport } from './routes/haven'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as TheWorkRouteImport } from './routes/the-work'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BasecampRoute = BasecampRouteImport.update({
  id: '/basecamp',
  path: '/basecamp',
  getParentRoute: () => rootRouteImport,
} as any)
const BootcampRoute = BootcampRouteImport.update({
  id: '/bootcamp',
  path: '/bootcamp',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const HavenRoute = HavenRouteImport.update({
  id: '/haven',
  path: '/haven',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const TheWorkRoute = TheWorkRouteImport.update({
  id: '/the-work',
  path: '/the-work',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/basecamp': typeof BasecampRoute
  '/bootcamp': typeof BootcampRoute
  '/builder': typeof BuilderRoute
  '/community': typeof CommunityRoute
  '/haven': typeof HavenRoute
  '/journal': typeof JournalRoute
  '/shop': typeof ShopRoute
  '/the-work': typeof TheWorkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/basecamp': typeof BasecampRoute
  '/bootcamp': typeof BootcampRoute
  '/builder': typeof BuilderRoute
  '/community': typeof CommunityRoute
  '/haven': typeof HavenRoute
  '/journal': typeof JournalRoute
  '/shop': typeof ShopRoute
  '/the-work': typeof TheWorkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/basecamp': typeof BasecampRoute
  '/bootcamp': typeof BootcampRoute
  '/builder': typeof BuilderRoute
  '/community': typeof CommunityRoute
  '/haven': typeof HavenRoute
  '/journal': typeof JournalRoute
  '/shop': typeof ShopRoute
  '/the-work': typeof TheWorkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/basecamp'
    | '/bootcamp'
    | '/builder'
    | '/community'
    | '/haven'
    | '/journal'
    | '/shop'
    | '/the-work'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/basecamp'
    | '/bootcamp'
    | '/builder'
    | '/community'
    | '/haven'
    | '/journal'
    | '/shop'
    | '/the-work'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/basecamp'
    | '/bootcamp'
    | '/builder'
    | '/community'
    | '/haven'
    | '/journal'
    | '/shop'
    | '/the-work'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BasecampRoute: typeof BasecampRoute
  BootcampRoute: typeof BootcampRoute
  BuilderRoute: typeof BuilderRoute
  CommunityRoute: typeof CommunityRoute
  HavenRoute: typeof HavenRoute
  JournalRoute: typeof JournalRoute
  ShopRoute: typeof ShopRoute
  TheWorkRoute: typeof TheWorkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/basecamp': {
      id: '/basecamp'
      path: '/basecamp'
      fullPath: '/basecamp'
      preLoaderRoute: typeof BasecampRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bootcamp': {
      id: '/bootcamp'
      path: '/bootcamp'
      fullPath: '/bootcamp'
      preLoaderRoute: typeof BootcampRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/haven': {
      id: '/haven'
      path: '/haven'
      fullPath: '/haven'
      preLoaderRoute: typeof HavenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/the-work': {
      id: '/the-work'
      path: '/the-work'
      fullPath: '/the-work'
      preLoaderRoute: typeof TheWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BasecampRoute: BasecampRoute,
  BootcampRoute: BootcampRoute,
  BuilderRoute: BuilderRoute,
  CommunityRoute: CommunityRoute,
  HavenRoute: HavenRoute,
  JournalRoute: JournalRoute,
  ShopRoute: ShopRoute,
  TheWorkRoute: TheWorkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
