/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BasecampRouteImport } from './routes/basecamp'
import { Route as BootcampRouteImport } from './routes/bootcamp'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as D14RouteImport } from './routes/d14'
import { Route as HavenRouteImport } from './routes/haven'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as TheWorkRouteImport } from './routes/the-work'
import { Route as VisitRouteImport } from './routes/visit'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminFridayRouteImport } from './routes/admin.friday'
import { Route as AdminInventoryRouteImport } from './routes/admin.inventory'
import { Route as AdminMoneyRouteImport } from './routes/admin.money'
import { Route as AdminPipelineRouteImport } from './routes/admin.pipeline'
import { Route as AdminRiskRouteImport } from './routes/admin.risk'
import { Route as BookRetreatRouteImport } from './routes/book.retreat'
import { Route as BookTreatmentRouteImport } from './routes/book.treatment'
import { Route as D14IndexRouteImport } from './routes/d14.index'
import { Route as D14BasecampRouteImport } from './routes/d14.basecamp'
import { Route as D14SeamRouteImport } from './routes/d14.seam'
import { Route as D14SpecimenRouteImport } from './routes/d14.specimen'
import { Route as ForTeamsRouteImport } from './routes/for.teams'
import { Route as HavenIndexRouteImport } from './routes/haven.index'
import { Route as HavenSlugRouteImport } from './routes/haven.$slug'
import { Route as JournalIndexRouteImport } from './routes/journal.index'
import { Route as JournalSlugRouteImport } from './routes/journal.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BasecampRoute = BasecampRouteImport.update({
  id: '/basecamp',
  path: '/basecamp',
  getParentRoute: () => rootRouteImport,
} as any)
const BootcampRoute = BootcampRouteImport.update({
  id: '/bootcamp',
  path: '/bootcamp',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const D14Route = D14RouteImport.update({
  id: '/d14',
  path: '/d14',
  getParentRoute: () => rootRouteImport,
} as any)
const HavenRoute = HavenRouteImport.update({
  id: '/haven',
  path: '/haven',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const TheWorkRoute = TheWorkRouteImport.update({
  id: '/the-work',
  path: '/the-work',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitRoute = VisitRouteImport.update({
  id: '/visit',
  path: '/visit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFridayRoute = AdminFridayRouteImport.update({
  id: '/friday',
  path: '/friday',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMoneyRoute = AdminMoneyRouteImport.update({
  id: '/money',
  path: '/money',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPipelineRoute = AdminPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRiskRoute = AdminRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => AdminRoute,
} as any)
const BookRetreatRoute = BookRetreatRouteImport.update({
  id: '/book/retreat',
  path: '/book/retreat',
  getParentRoute: () => rootRouteImport,
} as any)
const BookTreatmentRoute = BookTreatmentRouteImport.update({
  id: '/book/treatment',
  path: '/book/treatment',
  getParentRoute: () => rootRouteImport,
} as any)
const D14IndexRoute = D14IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => D14Route,
} as any)
const D14BasecampRoute = D14BasecampRouteImport.update({
  id: '/basecamp',
  path: '/basecamp',
  getParentRoute: () => D14Route,
} as any)
const D14SeamRoute = D14SeamRouteImport.update({
  id: '/seam',
  path: '/seam',
  getParentRoute: () => D14Route,
} as any)
const D14SpecimenRoute = D14SpecimenRouteImport.update({
  id: '/specimen',
  path: '/specimen',
  getParentRoute: () => D14Route,
} as any)
const ForTeamsRoute = ForTeamsRouteImport.update({
  id: '/for/teams',
  path: '/for/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const HavenIndexRoute = HavenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HavenRoute,
} as any)
const HavenSlugRoute = HavenSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => HavenRoute,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JournalRoute,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => JournalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/basecamp': typeof BasecampRoute
  '/bootcamp': typeof BootcampRoute
  '/builder': typeof BuilderRoute
  '/community': typeof CommunityRoute
  '/d14': typeof D14RouteWithChildren
  '/haven': typeof HavenRouteWithChildren
  '/journal': typeof JournalRouteWithChildren
  '/login': typeof LoginRoute
  '/shop': typeof ShopRoute
  '/the-work': typeof TheWorkRoute
  '/visit': typeof VisitRoute
  '/admin/friday': typeof AdminFridayRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/money': typeof AdminMoneyRoute
  '/admin/pipeline': typeof AdminPipelineRoute
  '/admin/risk': typeof AdminRiskRoute
  '/book/retreat': typeof BookRetreatRoute
  '/book/treatment': typeof BookTreatmentRoute
  '/d14/basecamp': typeof D14BasecampRoute
  '/d14/seam': typeof D14SeamRoute
  '/d14/specimen': typeof D14SpecimenRoute
  '/for/teams': typeof ForTeamsRoute
  '/haven/$slug': typeof HavenSlugRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/d14/': typeof D14IndexRoute
  '/haven/': typeof HavenIndexRoute
  '/journal/': typeof JournalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/basecamp': typeof BasecampRoute
  '/bootcamp': typeof BootcampRoute
  '/builder': typeof BuilderRoute
  '/community': typeof CommunityRoute
  '/login': typeof LoginRoute
  '/shop': typeof ShopRoute
  '/the-work': typeof TheWorkRoute
  '/visit': typeof VisitRoute
  '/admin/friday': typeof AdminFridayRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/money': typeof AdminMoneyRoute
  '/admin/pipeline': typeof AdminPipelineRoute
  '/admin/risk': typeof AdminRiskRoute
  '/book/retreat': typeof BookRetreatRoute
  '/book/treatment': typeof BookTreatmentRoute
  '/d14/basecamp': typeof D14BasecampRoute
  '/d14/seam': typeof D14SeamRoute
  '/d14/specimen': typeof D14SpecimenRoute
  '/for/teams': typeof ForTeamsRoute
  '/haven/$slug': typeof HavenSlugRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/admin': typeof AdminIndexRoute
  '/d14': typeof D14IndexRoute
  '/haven': typeof HavenIndexRoute
  '/journal': typeof JournalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/basecamp': typeof BasecampRoute
  '/bootcamp': typeof BootcampRoute
  '/builder': typeof BuilderRoute
  '/community': typeof CommunityRoute
  '/d14': typeof D14RouteWithChildren
  '/haven': typeof HavenRouteWithChildren
  '/journal': typeof JournalRouteWithChildren
  '/login': typeof LoginRoute
  '/shop': typeof ShopRoute
  '/the-work': typeof TheWorkRoute
  '/visit': typeof VisitRoute
  '/admin/friday': typeof AdminFridayRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/money': typeof AdminMoneyRoute
  '/admin/pipeline': typeof AdminPipelineRoute
  '/admin/risk': typeof AdminRiskRoute
  '/book/retreat': typeof BookRetreatRoute
  '/book/treatment': typeof BookTreatmentRoute
  '/d14/basecamp': typeof D14BasecampRoute
  '/d14/seam': typeof D14SeamRoute
  '/d14/specimen': typeof D14SpecimenRoute
  '/for/teams': typeof ForTeamsRoute
  '/haven/$slug': typeof HavenSlugRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/d14/': typeof D14IndexRoute
  '/haven/': typeof HavenIndexRoute
  '/journal/': typeof JournalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/basecamp'
    | '/bootcamp'
    | '/builder'
    | '/community'
    | '/d14'
    | '/haven'
    | '/journal'
    | '/login'
    | '/shop'
    | '/the-work'
    | '/visit'
    | '/admin/friday'
    | '/admin/inventory'
    | '/admin/money'
    | '/admin/pipeline'
    | '/admin/risk'
    | '/book/retreat'
    | '/book/treatment'
    | '/d14/basecamp'
    | '/d14/seam'
    | '/d14/specimen'
    | '/for/teams'
    | '/haven/$slug'
    | '/journal/$slug'
    | '/admin/'
    | '/d14/'
    | '/haven/'
    | '/journal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/basecamp'
    | '/bootcamp'
    | '/builder'
    | '/community'
    | '/login'
    | '/shop'
    | '/the-work'
    | '/visit'
    | '/admin/friday'
    | '/admin/inventory'
    | '/admin/money'
    | '/admin/pipeline'
    | '/admin/risk'
    | '/book/retreat'
    | '/book/treatment'
    | '/d14/basecamp'
    | '/d14/seam'
    | '/d14/specimen'
    | '/for/teams'
    | '/haven/$slug'
    | '/journal/$slug'
    | '/admin'
    | '/d14'
    | '/haven'
    | '/journal'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/basecamp'
    | '/bootcamp'
    | '/builder'
    | '/community'
    | '/d14'
    | '/haven'
    | '/journal'
    | '/login'
    | '/shop'
    | '/the-work'
    | '/visit'
    | '/admin/friday'
    | '/admin/inventory'
    | '/admin/money'
    | '/admin/pipeline'
    | '/admin/risk'
    | '/book/retreat'
    | '/book/treatment'
    | '/d14/basecamp'
    | '/d14/seam'
    | '/d14/specimen'
    | '/for/teams'
    | '/haven/$slug'
    | '/journal/$slug'
    | '/admin/'
    | '/d14/'
    | '/haven/'
    | '/journal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BasecampRoute: typeof BasecampRoute
  BootcampRoute: typeof BootcampRoute
  BuilderRoute: typeof BuilderRoute
  CommunityRoute: typeof CommunityRoute
  D14Route: typeof D14RouteWithChildren
  HavenRoute: typeof HavenRouteWithChildren
  JournalRoute: typeof JournalRouteWithChildren
  LoginRoute: typeof LoginRoute
  ShopRoute: typeof ShopRoute
  TheWorkRoute: typeof TheWorkRoute
  VisitRoute: typeof VisitRoute
  BookRetreatRoute: typeof BookRetreatRoute
  BookTreatmentRoute: typeof BookTreatmentRoute
  ForTeamsRoute: typeof ForTeamsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/basecamp': {
      id: '/basecamp'
      path: '/basecamp'
      fullPath: '/basecamp'
      preLoaderRoute: typeof BasecampRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bootcamp': {
      id: '/bootcamp'
      path: '/bootcamp'
      fullPath: '/bootcamp'
      preLoaderRoute: typeof BootcampRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d14': {
      id: '/d14'
      path: '/d14'
      fullPath: '/d14'
      preLoaderRoute: typeof D14RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/haven': {
      id: '/haven'
      path: '/haven'
      fullPath: '/haven'
      preLoaderRoute: typeof HavenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/the-work': {
      id: '/the-work'
      path: '/the-work'
      fullPath: '/the-work'
      preLoaderRoute: typeof TheWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visit': {
      id: '/visit'
      path: '/visit'
      fullPath: '/visit'
      preLoaderRoute: typeof VisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/friday': {
      id: '/admin/friday'
      path: '/friday'
      fullPath: '/admin/friday'
      preLoaderRoute: typeof AdminFridayRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/money': {
      id: '/admin/money'
      path: '/money'
      fullPath: '/admin/money'
      preLoaderRoute: typeof AdminMoneyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pipeline': {
      id: '/admin/pipeline'
      path: '/pipeline'
      fullPath: '/admin/pipeline'
      preLoaderRoute: typeof AdminPipelineRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/risk': {
      id: '/admin/risk'
      path: '/risk'
      fullPath: '/admin/risk'
      preLoaderRoute: typeof AdminRiskRouteImport
      parentRoute: typeof AdminRoute
    }
    '/book/retreat': {
      id: '/book/retreat'
      path: '/book/retreat'
      fullPath: '/book/retreat'
      preLoaderRoute: typeof BookRetreatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/treatment': {
      id: '/book/treatment'
      path: '/book/treatment'
      fullPath: '/book/treatment'
      preLoaderRoute: typeof BookTreatmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d14/': {
      id: '/d14/'
      path: '/'
      fullPath: '/d14/'
      preLoaderRoute: typeof D14IndexRouteImport
      parentRoute: typeof D14Route
    }
    '/d14/basecamp': {
      id: '/d14/basecamp'
      path: '/basecamp'
      fullPath: '/d14/basecamp'
      preLoaderRoute: typeof D14BasecampRouteImport
      parentRoute: typeof D14Route
    }
    '/d14/seam': {
      id: '/d14/seam'
      path: '/seam'
      fullPath: '/d14/seam'
      preLoaderRoute: typeof D14SeamRouteImport
      parentRoute: typeof D14Route
    }
    '/d14/specimen': {
      id: '/d14/specimen'
      path: '/specimen'
      fullPath: '/d14/specimen'
      preLoaderRoute: typeof D14SpecimenRouteImport
      parentRoute: typeof D14Route
    }
    '/for/teams': {
      id: '/for/teams'
      path: '/for/teams'
      fullPath: '/for/teams'
      preLoaderRoute: typeof ForTeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/haven/': {
      id: '/haven/'
      path: '/'
      fullPath: '/haven/'
      preLoaderRoute: typeof HavenIndexRouteImport
      parentRoute: typeof HavenRoute
    }
    '/haven/$slug': {
      id: '/haven/$slug'
      path: '/$slug'
      fullPath: '/haven/$slug'
      preLoaderRoute: typeof HavenSlugRouteImport
      parentRoute: typeof HavenRoute
    }
    '/journal/': {
      id: '/journal/'
      path: '/'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof JournalRoute
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof JournalRoute
    }
  }
}

interface AdminRouteChildren {
  AdminFridayRoute: typeof AdminFridayRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminMoneyRoute: typeof AdminMoneyRoute
  AdminPipelineRoute: typeof AdminPipelineRoute
  AdminRiskRoute: typeof AdminRiskRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminFridayRoute: AdminFridayRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminMoneyRoute: AdminMoneyRoute,
  AdminPipelineRoute: AdminPipelineRoute,
  AdminRiskRoute: AdminRiskRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface D14RouteChildren {
  D14BasecampRoute: typeof D14BasecampRoute
  D14SeamRoute: typeof D14SeamRoute
  D14SpecimenRoute: typeof D14SpecimenRoute
  D14IndexRoute: typeof D14IndexRoute
}

const D14RouteChildren: D14RouteChildren = {
  D14BasecampRoute: D14BasecampRoute,
  D14SeamRoute: D14SeamRoute,
  D14SpecimenRoute: D14SpecimenRoute,
  D14IndexRoute: D14IndexRoute,
}

const D14RouteWithChildren = D14Route._addFileChildren(D14RouteChildren)

interface HavenRouteChildren {
  HavenSlugRoute: typeof HavenSlugRoute
  HavenIndexRoute: typeof HavenIndexRoute
}

const HavenRouteChildren: HavenRouteChildren = {
  HavenSlugRoute: HavenSlugRoute,
  HavenIndexRoute: HavenIndexRoute,
}

const HavenRouteWithChildren = HavenRoute._addFileChildren(HavenRouteChildren)

interface JournalRouteChildren {
  JournalSlugRoute: typeof JournalSlugRoute
  JournalIndexRoute: typeof JournalIndexRoute
}

const JournalRouteChildren: JournalRouteChildren = {
  JournalSlugRoute: JournalSlugRoute,
  JournalIndexRoute: JournalIndexRoute,
}

const JournalRouteWithChildren =
  JournalRoute._addFileChildren(JournalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BasecampRoute: BasecampRoute,
  BootcampRoute: BootcampRoute,
  BuilderRoute: BuilderRoute,
  CommunityRoute: CommunityRoute,
  D14Route: D14RouteWithChildren,
  HavenRoute: HavenRouteWithChildren,
  JournalRoute: JournalRouteWithChildren,
  LoginRoute: LoginRoute,
  ShopRoute: ShopRoute,
  TheWorkRoute: TheWorkRoute,
  VisitRoute: VisitRoute,
  BookRetreatRoute: BookRetreatRoute,
  BookTreatmentRoute: BookTreatmentRoute,
  ForTeamsRoute: ForTeamsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
