// Generated by scripts/port-haven-photos.sh — do not edit by hand
export const HAVEN_PHOTOS = {
  "elowen": [
    "/images/haven/elowen/elowen-01.jpg",
    "/images/haven/elowen/elowen-02.jpg",
    "/images/haven/elowen/elowen-03.jpg",
    "/images/haven/elowen/elowen-04.jpg",
    "/images/haven/elowen/elowen-05.jpg",
    "/images/haven/elowen/elowen-06.jpg",
    "/images/haven/elowen/elowen-07.jpg",
    "/images/haven/elowen/elowen-08.jpg",
    "/images/haven/elowen/elowen-09.jpg",
    "/images/haven/elowen/elowen-10.jpg",
    "/images/haven/elowen/elowen-11.jpg",
    "/images/haven/elowen/elowen-12.jpg",
    "/images/haven/elowen/elowen-13.jpg"
  ],
  "hidden-hollow": [
    "/images/haven/hidden-hollow/hidden-hollow-01.jpg",
    "/images/haven/hidden-hollow/hidden-hollow-02.jpg",
    "/images/haven/hidden-hollow/hidden-hollow-03.jpg",
    "/images/haven/hidden-hollow/hidden-hollow-04.jpg",
    "/images/haven/hidden-hollow/hidden-hollow-05.jpg"
  ],
  "river-blossom": [
    "/images/haven/river-blossom/river-blossom-01.jpg",
    "/images/haven/river-blossom/river-blossom-02.jpg",
    "/images/haven/river-blossom/river-blossom-03.jpg",
    "/images/haven/river-blossom/river-blossom-04.jpg",
    "/images/haven/river-blossom/river-blossom-05.jpg",
    "/images/haven/river-blossom/river-blossom-06.jpg",
    "/images/haven/river-blossom/river-blossom-07.jpg",
    "/images/haven/river-blossom/river-blossom-08.jpg",
    "/images/haven/river-blossom/river-blossom-09.jpg",
    "/images/haven/river-blossom/river-blossom-10.jpg"
  ],
  "water-mark": [
    "/images/haven/water-mark/water-mark-01.jpg",
    "/images/haven/water-mark/water-mark-02.jpg",
    "/images/haven/water-mark/water-mark-03.jpg",
    "/images/haven/water-mark/water-mark-04.jpg",
    "/images/haven/water-mark/water-mark-05.jpg",
    "/images/haven/water-mark/water-mark-06.jpg",
    "/images/haven/water-mark/water-mark-07.jpg",
    "/images/haven/water-mark/water-mark-08.jpg",
    "/images/haven/water-mark/water-mark-09.jpg",
    "/images/haven/water-mark/water-mark-10.jpg",
    "/images/haven/water-mark/water-mark-11.jpg",
    "/images/haven/water-mark/water-mark-12.jpg",
    "/images/haven/water-mark/water-mark-13.jpg"
  ],
  "exterior": [
    "/images/haven/exterior/exterior-01.jpg",
    "/images/haven/exterior/exterior-02.jpg",
    "/images/haven/exterior/exterior-03.jpg",
    "/images/haven/exterior/exterior-04.jpg",
    "/images/haven/exterior/exterior-05.jpg",
    "/images/haven/exterior/exterior-06.jpg",
    "/images/haven/exterior/exterior-07.jpg",
    "/images/haven/exterior/exterior-08.jpg",
    "/images/haven/exterior/exterior-09.jpg",
    "/images/haven/exterior/exterior-10.jpg",
    "/images/haven/exterior/exterior-11.jpg",
    "/images/haven/exterior/exterior-12.jpg"
  ],
} as const;
